Feature
atenaiis/restaurant-pg pull request #1
Opened 2021-05-21 22:51 UTC by atenaiis

Good afternoon,

The goal of this project is to demonstrate mastery with DOM manipulation by dynamically rendering a simple restaurant's homepage.

Please follow read me file instructions to check this project.

Cheers

Mariana Campos

2021-05-22 11:36 UTC, afanimartin requested changes
### Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this PR. 
### Highlights 🌵 🌵 🌵 
- Use of modules
- Required packages added to `package.json`

### Changes 🙅🏿 🙅🏿 🙅🏿 
- Remove all comments from the codebase. They make your code look ugly
- Update the readme. Check comments


### Martin Afani
#### Slack: whiz25

2021-05-22 11:36 UTC, afanimartin commented on README.md
> +- Navigate to the Repo Folder
- Add command for doing that

2021-05-22 11:36 UTC, afanimartin commented on README.md
> +- Use your favorite browser to open the index.html file (located at the dist page)
- dist page or folder? Be more explicit in your instructions.

2021-05-22 11:36 UTC, afanimartin commented on README.md
> +## Show your support
- Add open-source license such as MIT

2021-05-22 11:36 UTC, afanimartin commented on src/contact.js
> +  // Set H1
- Remove all comments here

2021-05-22 11:36 UTC, afanimartin commented on src/home.js
> +  // Set H1
- Remove comments

2021-05-22 11:36 UTC, afanimartin commented on src/menu.js
> +  // Set H1
- Remove comments

2021-05-22 11:36 UTC, afanimartin commented on src/load.js
> +// Creating Website Logo
- Remove comments

2021-05-22 11:36 UTC, afanimartin commented on src/index.js
> +// Getting Div Sections where the elements will be appended
- Remove all comments

2021-05-24 16:37 UTC, rukundoeric approved these changes
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow. 💯 
  - App is functionsl and available online. 💯 
  - It looks nice 💯
  
- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-05-24 16:49 UTC, merged